#!/usr/bin/env python

Import("env")
Import("env_modules")

# Compilation
julia_include = env["julia_include"]
env_julia = env_modules.Clone()
env_julia.Append(CPPPATH=[julia_include])
env_julia.add_source_files(env.modules_sources, "*.cpp")

# Linking
julia_lib = env["julia_lib"]
env.Append(LIBPATH=[julia_lib])
env.Append(LIBS=["julia"])
env.Append(
    LINKFLAGS=[
        '-Wl,-rpath,"' + julia_lib + '"',
    ]
)

if env.editor_build:
    env_julia.add_source_files(env.modules_sources, "editor/*.cpp")
